### ISSUE TITLE
Reach out to DRC to schedule usability test with screen reader user(s)

### ISSUE THREAD

**Issue by liamstar97** [Negative-Carbon-Reforestation-Project/openlayers-springboot-react-demo#36]

**Comment by asathkumara** [comment]
Reached out to DRC, they don't offer any availability for screen reader testing they said. Followed up with other departments as recommended by them, waiting to hear back.

**Comment by asathkumara** [comment]
Brian, the usability tester got back to me with his evaluation. To summarize, we are A and AA compliant under WCAG 2.0 but not WCAG 2.1 since we have to pass all the tests. I will be working towards that on the next UI.

[Here's a video](https://www.youtube.com/watch?v=a8t3ijqtXQw) I stitched from his test session recordings and the notes he included are on the same spreadsheet where I kept my [usability testing notes](https://docs.google.com/spreadsheets/d/1dS2DAReOCuF6j-XCDFlVBMnOskZRd0NDVGY9gddJXJo/edit?usp=sharing).
